development:
  dialect: postgres
  database: postgres
  user: ryon
  password: 168168wstc
  host: blog.caecmzuazhif.us-west-2.rds.amazonaws.com
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/blog_app_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/blog_app_production?sslmode=disable"}}
